services:
  uae-8sa-demo-feria-dev:
    container_name: uae-8sa-demo-feria-dev
    entrypoint: yarn run web
    environment:
      - TZ=America/Guayaquil
    hostname: uae-8sa-demo-feria-dev
    image: node:18
    #networks:
      #- 71walceli_https-proxy
      #- uae-pis-backend
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - 19000-19010:19000-19010
    volumes:
      - ./App:/App
    working_dir: /App